<?php

$departments = [
    'bengali' => 'Bangla',
    'english' => 'English',
    'economics' => 'Economics',
    'political_science' => 'Political Science',
    'public_administration' => 'Public Administration',
    'islamic_history_and_culture' => 'Islamic History & Culture',
    'fine_arts' => 'Fine Arts',
    'sociology' => 'Sociology',
    'history' => 'History',
    'islamic_studies' => 'Islamic Studies',
    'philosophy' => 'Philosophy',
    'arabic' => 'arabic',
    'pali' => 'Pali',
    'physics' => 'Physics',
    'chemistry' => 'Chemistry',
    'botany' => 'Botany',
    'Zoology' => 'Zoology',
    'mathematics' => 'Mathematics',
    'dtatistics' => 'Statistics',
    'marine_science_and_fisheries' => 'Marine Science & Fisheries',
    'forestry' => 'forestry',
    'accounting_bba' => 'Accounting BBA',
    'management_bba' => 'Management BBA',
    'public_finance_bba' => 'Public Finance BBA',
    'marketing_bba' => 'Marketing BBA',
    'accounting' => 'Accounting',
    'management' => 'Management',
    'marketing' => 'Marketing',
    'public_finance' => 'Public Finance',

];